export const Users = [
  {
    id: 1,
    profilePicture: "persons/black1.jpg",
    username: "Ettila Eumi",
  },
  {
    id: 2,
    profilePicture: "persons/black1.jpg",
    username: "Faysal Sohan",
  },
  {
    id: 3,
    profilePicture: "persons/black1.jpg",
    username: "Istiak Fahim",
  },
  {
    id: 4,
    profilePicture: "persons/black1.jpg",
    username: "Jahid Hasan Nishat",
  },
  {
    id: 5,
    profilePicture: "persons/black1.jpg",
    username: "Mahadi Al Hasan",
  },
  {
    id: 6,
    profilePicture: "persons/black1.jpg",
    username: "Md Nazmus Sakib",
  },
  {
    id: 7,
    profilePicture: "persons/black1.jpg",
    username: "Mehedi Hasan Rony",
  },
  {
    id: 8,
    profilePicture: "persons/black1.jpg",
    username: "Mehedi Rishad Hasan ",
  },
  {
    id: 9,
    profilePicture: "persons/black1.jpg",
    username: "Munem Munna",
  },
  {
    id: 10,
    profilePicture: "persons/black1.jpg",
    username: "Munem Shahriar",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "persons/black1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "persons/black1.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "persons/black1.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "persons/black1.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "persons/black1.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "persons/black1.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "persons/black1.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "persons/black1.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "persons/black1.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "persons/black1.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
